### ISSUE TITLE
Errors after uninstall this plugin

### ISSUE THREAD

**Issue by toptnc** [frywer/custom_tables#22]
Since my previous issue I have uninstalled this plugin, but after that I get errors with other components of redmine like custom fields or the calendar. In production.log I can see several errors of this type.

`Started GET "/projects/2193_m-add-a-suite_ad/issues" for 89.107.242.213 at 2020-06-09 10:14:19 +0200
Processing by IssuesController#index as HTML
  Parameters: {"project_id"=>"2193_m-add-a-suite_ad"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 24ms (ActiveRecord: 11.9ms)

ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'CustomEntityCustomField'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite CustomField.inheritance_column to use another column for that information.):

app/models/query.rb:1381:in `group_by'
app/models/query.rb:1381:in `add_associations_custom_fields_filters'
app/models/issue_query.rb:209:in `initialize_available_filters'
app/models/query.rb:652:in `available_filters'
plugins/redmine_checklists/lib/redmine_checklists/patches/issue_query_patch.rb:41:in `available_filters_with_checklists'
app/models/query.rb:403:in `build_from_params'
app/models/issue_query.rb:92:in `build_from_params'
app/helpers/queries_helper.rb:314:in `retrieve_query'
app/controllers/issues_controller.rb:46:in `index'
plugins/redmine_issues_tree/lib/redmine_issues_tree/issues_controller_patch.rb:17:in `index'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:72:in `call'
Started GET "/projects/2193_m-add-a-suite_ad/issues/calendar" for 89.107.242.213 at 2020-06-09 10:14:25 +0200
Processing by CalendarsController#show as HTML
  Parameters: {"project_id"=>"2193_m-add-a-suite_ad"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 30ms (ActiveRecord: 14.7ms)

ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'CustomEntityCustomField'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite CustomField.inheritance_column to use another column for that information.):

app/models/query.rb:1381:in `group_by'
app/models/query.rb:1381:in `add_associations_custom_fields_filters'
app/models/issue_query.rb:209:in `initialize_available_filters'
app/models/query.rb:652:in `available_filters'
plugins/redmine_checklists/lib/redmine_checklists/patches/issue_query_patch.rb:41:in `available_filters_with_checklists'
app/models/query.rb:403:in `build_from_params'
app/models/issue_query.rb:92:in `build_from_params'
app/helpers/queries_helper.rb:314:in `retrieve_query'
app/controllers/calendars_controller.rb:42:in `show'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:72:in `call'
`

I reinstalled the custom_tables plugin, although I can't use it because It doesn't work in conjunction with redmine_checklists.

**Comment by toptnc** [comment]
I don't know if this workaround is enough but I have deleted al the 'CustomEntityCustomField' rows in 'custom_fields' table and now all seems to work ok.
