### ISSUE TITLE
not comptiable with redmine_computed_custom_field

### ISSUE THREAD

**Issue by ashrafalzyoud** [frywer/custom_tables#23]
can u compitable with this plugin
becuase i need formula in this plugin
https://github.com/annikoff/redmine_plugin_computed_custom_field

**Comment by Mikhail-Kukharenko** [comment]
I support this issue.
I have price , qty, discount and really want to have cost field computable.
Thank you!

**Comment by majioa** [comment]
@ashrafalzyoud what is the problem with joint usage the modules?

**Comment by Mikhail-Kukharenko** [comment]
The problem is following:
I can define some field in the Table as Calcilated (Formula). See attach (calculated_cf.png). In the formula for this field I use other  fields. The possibility to have calclated field is provided by plugin https://github.com/annikoff/redmine_plugin_computed_custom_field 
But when i create or change record for the table - this "calculated" field is not calculated at all. (edit_table_record.png)
Log shows nothing special, no errors.
![edit_table_record](https://user-images.githubusercontent.com/64480421/97416749-e614d800-1917-11eb-8c9a-0486c4afb6e8.png)
![calculated_cf](https://user-images.githubusercontent.com/64480421/97416752-e6ad6e80-1917-11eb-818c-62f4472848c5.png)

**Comment by san199332** [comment]
I am attaching a patch that fixes this problem.
[computed_custom_field.zip](https://github.com/frywer/custom_tables/files/5456934/computed_custom_field.zip)

**Comment by majioa** [comment]
> I am attaching a patch that fixes this problem.
> [computed_custom_field.zip](https://github.com/frywer/custom_tables/files/5456934/computed_custom_field.zip)

could you provide PR?

**Comment by sami79** [comment]
> I am attaching a patch that fixes this problem.
> [computed_custom_field.zip](https://github.com/frywer/custom_tables/files/5456934/computed_custom_field.zip)

please how to apply this patch ?
thank you

**Comment by sami79** [comment]
> I am attaching a patch that fixes this problem.
> [computed_custom_field.zip](https://github.com/frywer/custom_tables/files/5456934/computed_custom_field.zip)

worked nicely for me. thank you

**Comment by san199332** [comment]
https://github.com/san199332/redmine_plugin_computed_custom_field with patch applied

**Comment by ashrafalzyoud** [comment]
@san199332 
can u help why the user cant view the table

**Comment by san199332** [comment]
> @san199332 can u help why the user cant view the table

I propose a temporary solution to this problem, apply this patch to your redmine.
```
diff --git a/app/helpers/application_helper.rb b/app/helpers/application_helper.rb
index fbccbe0..a7d3fd1 100644
--- a/app/helpers/application_helper.rb
+++ b/app/helpers/application_helper.rb
@@ -295,7 +295,7 @@ module ApplicationHelper
         object.filename
       end
     when 'CustomValue', 'CustomFieldValue'
-      return "" unless object.customized&.visible?
+      #return "" unless object.customized&.visible?
       if object.custom_field
         f = object.custom_field.format.formatted_custom_value(self, object, html)
         if f.nil? || f.is_a?(String)
```

**Comment by ashrafalzyoud** [comment]
@san199332 
Thx for reply brother
Are u test it ?!

Can u fork it with compitable views users &computed custom field

**Comment by san199332** [comment]
> @san199332 Thx for reply brother Are u test it ?!

Yes, it's tested and works.

> Can u fork it with compitable views users &computed custom field

This is a patch for the redmine kernel, so I can't.

**Comment by ashrafalzyoud** [comment]
@san199332 
I will test it now
🙏 Thx brother

**Comment by ashrafalzyoud** [comment]
> > @san199332 can u help why the user cant view the table
> 
> I propose a temporary solution to this problem, apply this patch to your redmine.
> 
> ```
> diff --git a/app/helpers/application_helper.rb b/app/helpers/application_helper.rb
> index fbccbe0..a7d3fd1 100644
> --- a/app/helpers/application_helper.rb
> +++ b/app/helpers/application_helper.rb
> @@ -295,7 +295,7 @@ module ApplicationHelper
>          object.filename
>        end
>      when 'CustomValue', 'CustomFieldValue'
> -      return "" unless object.customized&.visible?
> +      #return "" unless object.customized&.visible?
>        if object.custom_field
>          f = object.custom_field.format.formatted_custom_value(self, object, html)
>          if f.nil? || f.is_a?(String)
> ```

this changes in redmine core,,can u do changes in same plugin
i cant make change in core redmine,this dangerous

**Comment by san199332** [comment]
> this changes in redmine core,,can u do changes in same plugin
Try to apply my last commit
https://github.com/san199332/custom_tables/commit/fbf44a9566b03c83211064e7fe9eb1080c107c75

**Comment by ashrafalzyoud** [comment]
@san199332 
thx for your help brother
the user now can show the table but when i edit the value
give ne internal error
```
NoMethodError (undefined method `customer' for nil:NilClass

          if issue.customer && is_send_note && notes
                  ^^^^^^^^^):
  
plugins/redmine_contacts_helpdesk/lib/redmine_helpdesk/patches/journal_patch.rb:43:in `send_note'
app/models/journal.rb:102:in `save'
plugins/custom_tables/lib/custom_tables/acts_as_journalize.rb:59:in `create_journal'
plugins/custom_tables/app/controllers/custom_entities_controller.rb:92:in `update'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by ashrafalzyoud** [comment]
@san199332 
im try also delete the helpdisk plugin

the same error when in edit the table
```
NoMethodError (undefined method `notified_mentions' for #<CustomEntity id: 8, custom_table_id: 3, author_id: 114, created_at: "2022-12-15 22:20:49.000000000 +0000", updated_at: "2022-12-15 22:26:16.000000000 +0000", type: nil, issue_id: 3332>
Did you mean?  notified_users):
  
app/models/mailer.rb:132:in `deliver_issue_edit'
app/models/journal.rb:354:in `send_notification'
app/models/journal.rb:102:in `save'
plugins/custom_tables/lib/custom_tables/acts_as_journalize.rb:59:in `create_journal'
plugins/custom_tables/app/controllers/custom_entities_controller.rb:92:in `update'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by san199332** [comment]
@ashrafalzyoud Update and the problem will go away
https://github.com/san199332/custom_tables/commit/9ec4f63eaa03280c6b9d5cb1d904a9e1d22ac9fa

**Comment by san199332** [comment]
@ashrafalzyoud Apply the helpdesk patch and the error will go away
[helpdesk.zip](https://github.com/frywer/custom_tables/files/10244004/helpdesk.zip)

**Comment by ashrafalzyoud** [comment]
@san199332 
Thx brother
U are Intelligent and collaborative
,

**Comment by ashrafalzyoud** [comment]
@san199332 
Can u check bulk_edit if it's work?

**Comment by ashrafalzyoud** [comment]
@san199332  plz if u can help

**Comment by san199332** [comment]
@ashrafalzyoud Try this fix
https://github.com/san199332/custom_tables/commit/fda02cad321118bbb2488f81d99490ee628a70ed

**Comment by ashrafalzyoud** [comment]
thx for all your help
the custom field type file now its working
but the problem now
**the user cant edit the table**
@san199332

**Comment by san199332** [comment]
@ashrafalzyoud 
https://github.com/san199332/custom_tables/commit/1527dfda3dffd7f754aace90be89575021e1fb8e

**Comment by san199332** [comment]
> I'm try the old one code its working good
> 
> What the difference between the last code?!
> 
> What releases code @san199332

The last code corrects the import of issues in csv.

**Comment by ashrafalzyoud** [comment]
perfect man @san199332 
thx for u alot

**Comment by ashrafalzyoud** [comment]
@san199332 how are u my brother
every things work ok
but the user dont have **show** field but he have (edit,delete)

**Comment by ashrafalzyoud** [comment]
Any update plz
To user can show her table
@san199332

**Comment by san199332** [comment]
> Any update plz To user can show her table @san199332

https://github.com/san199332/custom_tables/commit/02451394f3dcc73d6e24fcd448bc0959a5d73e7e Fix in last commit

**Comment by ashrafalzyoud** [comment]
@san199332 
thx for u and your support its working
- the user or her group can see the all data in custom table if the table shared to multi project 
- they must rule depend the policy permision view he see only the date in her project only
